---
version: '2.4'

services:
  database:
    build:
      context: lib/src/test/resources/postgres
      dockerfile: Dockerfile-16.0
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    volumes:
      - data:/var/lib/postgresql/data
    network_mode: host
    command: [ "postgres", "-c", "wal_level=logical" ]

volumes:
  data:
    driver_opts:
      type: tmpfs
      device: tmpfs
